spring:
  jpa:
    generate-ddl: true
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/bookstore_db}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    hikari:
      schema: bookstore_schema
      connection-timeout: 10000
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

app:
  redis:
    enable: true
  cache:
    cacheType: redis
    cache-names:
      - filterByTitleAndAuthorCache
      - categoryCache
    caches:
      filterByTitleAndAuthorCache:
        expiry: 10m
      categoryCache:
        expiry: 10m
